import { deepFreeze, reconcileChange } from './domain.mjs';
import { createMetricRule } from './metric-catalog.mjs';
import { createTrendSeries } from './trend-evidence.mjs';

function check(input) {
  return {
    priority: 'required',
    window: '变更前 15 分钟 vs 变更后 15 分钟',
    baseline: '过去 7 天同星期、同时段',
    severity: 'critical',
    ...input,
  };
}

const naturalLanguagePass = {
  id: 'natural-language-pass',
  entryKind: 'natural-language',
  eyebrow: 'Journey 01 · Natural language',
  title: '订单服务升级验收',
  subtitle: '订单发布验证',
  prompt: '今晚升级 order-api v4.8.0，帮我确认订单提交和支付链路有没有问题。',
  declaredChange: {
    id: 'MANUAL-ORDER-480',
    summary: 'order-api v4.8.0 应用代码升级',
    version: 'v4.8.0',
    entities: ['order-api', 'payment-gateway', 'order-cache'],
    fingerprint: 'image:order-api@sha256:4e80',
  },
  observedChange: {
    summary: '运行时版本与声明一致',
    entities: ['order-api', 'payment-gateway', 'order-cache'],
    fingerprint: 'image:order-api@sha256:4e80',
  },
  impactDimensions: {
    businessJourney: ['订单提交 → 支付确认'],
    goldenMetrics: ['order.submit.success_rate', 'payment.confirm.success_rate'],
    traceDependencies: ['order-api → payment-gateway'],
    middleware: ['order-cache · Redis'],
  },
  contextSources: [
    {
      id: 'nl-intent',
      kind: '自然语义',
      label: 'SRE 巡检意图',
      detail: '识别服务、版本、订单提交与支付确认两个业务目标',
      freshness: '刚刚',
    },
    {
      id: 'order-graph',
      kind: '业务图谱',
      label: '订单黄金旅程',
      detail: '订单提交 → 支付确认；绑定成功率与支付完成率',
      freshness: '2 小时前',
    },
    {
      id: 'order-trace',
      kind: 'Trace',
      label: '近 24h 真实调用',
      detail: 'order-api → payment-gateway；order-api → order-cache',
      freshness: '3 分钟前',
    },
    {
      id: 'metric-catalog',
      kind: '指标目录',
      label: '已注册执行能力',
      detail: '业务、服务、缓存与拨测指标均可直接执行',
      freshness: '当前',
    },
  ],
  hypotheses: ['新版本不能降低订单提交成功率', 'order-api 延迟与错误率不能显著退化', '支付依赖与缓存不能成为新增瓶颈'],
  candidateChecks: [
    check({
      id: 'candidate-memory-trend',
      priority: 'recommended',
      criticality: 'medium',
      purpose: '识别升级后的缓慢内存爬升',
      entity: 'order-api',
      capability: '容器资源趋势',
      metricRules: [createMetricRule('container.memory.working_set', '<=', 1, { editable: false })],
      failureAction: '延长观察窗口',
      rationale: '历史复盘出现过长尾内存增长，但本次代码差异未触及缓存模块。',
      sourceRefs: ['nl-intent', 'metric-catalog'],
    }),
  ],
  committedChecks: [
    check({
      id: 'order-success',
      purpose: '保护订单提交业务结果',
      entity: '订单提交旅程',
      capability: '业务黄金指标',
      metricRules: [createMetricRule('order.submit.success_rate', '>=', 99.59)],
      failureAction: '暂停发布并转 RC Agent',
      rationale: '业务图谱将 order-api 绑定为订单提交的关键服务。',
      sourceRefs: ['nl-intent', 'order-graph', 'metric-catalog'],
    }),
    check({
      id: 'service-golden-signals',
      purpose: '验证服务自身没有退化',
      entity: 'order-api',
      capability: '服务黄金信号',
      metricRules: [createMetricRule('http.error_rate', '<=', 0.5), createMetricRule('http.duration.p95', '<=', 198)],
      failureAction: '暂停并检查新版本实例',
      rationale: '版本升级直接改变 order-api 运行时行为。',
      sourceRefs: ['nl-intent', 'metric-catalog'],
    }),
    check({
      id: 'payment-dependency',
      purpose: '验证关键下游支付确认',
      entity: 'payment-gateway',
      capability: 'Trace 依赖门禁',
      metricRules: [
        createMetricRule('span.client.error_rate', '<=', 0),
        createMetricRule('span.client.duration.p95.change_rate', '<=', 8),
      ],
      failureAction: '暂停并下钻支付 Trace',
      rationale: '真实 Trace 证明订单提交同步调用 payment-gateway。',
      sourceRefs: ['order-graph', 'order-trace', 'metric-catalog'],
    }),
    check({
      id: 'cache-health',
      purpose: '验证订单缓存无新增饱和',
      entity: 'order-cache',
      capability: 'Redis 开箱指标',
      metricRules: [createMetricRule('redis.hit_rate', '>=', 94.4), createMetricRule('redis.command_latency', '<=', 6)],
      failureAction: '标记条件放行并延长观察',
      rationale: 'Trace 证明 order-api 实际访问 order-cache。',
      sourceRefs: ['order-trace', 'metric-catalog'],
    }),
  ],
  execution: [
    { id: 'baseline', label: '锁定变更前基线', status: 'Verified', fact: '四类关键证据均新鲜可比' },
    { id: 'business', label: '验证业务黄金指标', status: 'Verified', fact: '订单成功率 99.82%，较基线 +0.03pp' },
    { id: 'service', label: '验证服务与 Trace', status: 'Verified', fact: 'p95 +3.2%，依赖无新增错误' },
    { id: 'middleware', label: '验证缓存与拨测', status: 'Verified', fact: '命中率 96.4%，多地拨测通过' },
  ],
  report: {
    evidenceVerdict: 'Verified',
    action: 'Proceed',
    actionLabel: '建议继续发布',
    title: '声明范围内未发现异常退化',
    summary: '订单提交、支付依赖、服务黄金信号与缓存均通过确定性验证。',
    scopeStatement: '结论覆盖订单提交与支付确认旅程，以及 Trace 证明的直接依赖。',
    evidenceCounts: { verified: 4, violated: 0, unresolved: 0 },
    keyEvidence: [
      '订单提交成功率 99.82%，较基线 +0.03pp',
      'order-api p95 186ms，较稳定版本 +3.2%',
      'payment-gateway 无新增错误 Trace',
    ],
    checkResults: [
      {
        checkId: 'order-success',
        status: 'Verified',
        summary: '订单提交成功率 99.82%，较基线 +0.03pp',
        measurements: [
          {
            id: 'order-success-rate',
            metricId: 'order.submit.success_rate',
            label: '订单提交成功率',
            entity: '订单提交旅程',
            kind: 'numeric',
            value: 99.82,
            unit: '%',
            displayValue: '99.82%',
            series: createTrendSeries(99.78, 99.8, 99.81, 99.83, 99.82, 99.82),
            gate: { operator: '>=', value: 99.59, unit: '%', displayValue: '下降不超过 0.20pp' },
          },
        ],
      },
      {
        checkId: 'service-golden-signals',
        status: 'Verified',
        summary: 'order-api p95 186ms，较稳定版本 +3.2%',
        measurements: [
          {
            id: 'order-api-p95',
            metricId: 'http.duration.p95',
            label: '服务延迟 p95',
            entity: 'order-api',
            kind: 'numeric',
            value: 186,
            unit: 'ms',
            displayValue: '186ms',
            series: createTrendSeries(179, 181, 184, 188, 185, 186),
            gate: { operator: '<=', value: 198, unit: 'ms', displayValue: '增幅 ≤ 10%' },
          },
          {
            id: 'order-api-error-rate',
            metricId: 'http.error_rate',
            label: '服务错误率',
            entity: 'order-api',
            kind: 'numeric',
            value: 0.18,
            unit: '%',
            displayValue: '0.18%',
            series: createTrendSeries(0.12, 0.14, 0.16, 0.2, 0.17, 0.18),
            gate: { operator: '<=', value: 0.5, unit: '%', displayValue: '≤ 0.5%' },
          },
        ],
      },
      {
        checkId: 'payment-dependency',
        status: 'Verified',
        summary: 'payment-gateway 无新增错误 Trace',
        measurements: [
          {
            id: 'payment-trace-errors',
            metricId: 'span.client.error_rate',
            label: '支付依赖错误 Trace',
            entity: 'payment-gateway',
            kind: 'numeric',
            value: 0,
            unit: '%',
            displayValue: '0%',
            series: createTrendSeries(0, 0, 0, 0, 0, 0),
            gate: { operator: '<=', value: 0, unit: '%', displayValue: '≤ 0%' },
          },
          {
            id: 'payment-trace-duration-change',
            metricId: 'span.client.duration.p95.change_rate',
            label: '下游依赖延迟增幅',
            entity: 'payment-gateway',
            kind: 'numeric',
            value: 3.2,
            unit: '%',
            displayValue: '+3.2%',
            series: createTrendSeries(1.6, 2, 2.4, 3.5, 3.1, 3.2),
            gate: { operator: '<=', value: 8, unit: '%', displayValue: '≤ 8%' },
          },
        ],
      },
      {
        checkId: 'cache-health',
        status: 'Verified',
        summary: 'order-cache 命令 p99 3.8ms，低于 6ms 门禁',
        measurements: [
          {
            id: 'order-cache-hit-rate',
            metricId: 'redis.hit_rate',
            label: '缓存命中率',
            entity: 'order-cache',
            kind: 'numeric',
            value: 96.4,
            unit: '%',
            displayValue: '96.4%',
            series: createTrendSeries(96.1, 96.2, 96.5, 96.3, 96.4, 96.4),
            gate: { operator: '>=', value: 94.4, unit: '%', displayValue: '≥ 94.4%' },
          },
          {
            id: 'order-cache-p99',
            metricId: 'redis.command_latency',
            label: '缓存命令 p99',
            entity: 'order-cache',
            kind: 'numeric',
            value: 3.8,
            unit: 'ms',
            displayValue: '3.8ms',
            series: createTrendSeries(3.1, 3.3, 3.6, 4, 3.7, 3.8),
            gate: { operator: '<=', value: 6, unit: 'ms', displayValue: '≤ 6ms' },
          },
        ],
      },
      {
        checkId: 'candidate-memory-trend',
        status: 'Inconclusive',
        summary: '短窗口不足以判断缓慢内存爬升',
        measurements: [
          {
            id: 'order-memory-trend',
            metricId: 'container.memory.working_set',
            label: '内存变化趋势',
            entity: 'order-api',
            kind: 'qualitative',
            displayValue: '短窗口证据不足',
            gate: { displayValue: '斜率低于历史同版本 P95' },
          },
        ],
      },
    ],
    interpretation: {
      whatHappened: {
        text: '订单提交成功率保持稳定，服务延迟未触及门禁。',
        evidenceIds: ['order-success-rate', 'order-api-p95'],
      },
      likelyCause: { text: '证据不足', evidenceIds: [] },
      recommendedAction: {
        text: '按当前节奏继续发布，并保持原观察窗口。',
        evidenceIds: ['order-success-rate', 'order-api-p95'],
      },
    },
    residualRisks: ['内存趋势为建议项，未纳入本次硬门禁。'],
    rcAgent: null,
  },
};

const changeTicketRisk = {
  id: 'change-ticket-risk',
  entryKind: 'change-ticket',
  eyebrow: 'Release validation · Change ticket',
  title: '支付配置发布巡检',
  subtitle: '声明范围内执行门禁，声明外影响保持为显式覆盖缺口',
  prompt: '变更单 CHG-84501：调整 payment-api Redis 超时 80ms → 120ms，灰度 25%。',
  declaredChange: {
    id: 'CHG-84501',
    summary: 'payment-api Redis 超时 80ms → 120ms',
    version: 'config-2026.08.06.2',
    entities: ['payment-api'],
    fingerprint: 'config:payment-timeout@91fa',
  },
  observedChange: {
    summary: '共享配置包同时作用于结算 DB 与发票异步任务',
    entities: ['payment-api', 'settlement-db', 'invoice-worker'],
    fingerprint: 'config:shared-payment-stack@c2bd',
  },
  impactDimensions: {
    businessJourney: ['支付确认 → 账单异步'],
    goldenMetrics: ['payment.confirm.success_rate'],
    traceDependencies: ['payment-api → settlement-db'],
    middleware: ['settlement-db · Redis · invoice queue'],
  },
  contextSources: [
    {
      id: 'change-ticket',
      kind: '电子流',
      label: 'CHG-84501',
      detail: '声明仅调整 payment-api Redis 超时',
      freshness: '刚刚',
    },
    {
      id: 'runtime-diff',
      kind: '运行时对账',
      label: 'Observed-Superset',
      detail: '共享配置 hash 影响 payment-api、settlement-db、invoice-worker',
      freshness: '1 分钟前',
    },
    {
      id: 'payment-graph',
      kind: '业务图谱',
      label: '支付确认旅程',
      detail: '支付确认依赖 settlement-db，invoice-worker 为异步账单链路',
      freshness: '5 小时前',
    },
    {
      id: 'payment-trace',
      kind: 'Trace',
      label: '灰度调用样本',
      detail: 'payment-api → settlement-db 连接等待升高',
      freshness: '2 分钟前',
    },
    {
      id: 'middleware-catalog',
      kind: '指标目录',
      label: 'DB / Redis 开箱能力',
      detail: '连接等待、池占用、慢查询和 Redis 延迟可执行',
      freshness: '当前',
    },
  ],
  hypotheses: ['共享配置不能造成数据库连接池饱和', '支付确认成功率不能退化', '发票异步积压不能扩大'],
  candidateChecks: [
    check({
      id: 'candidate-db-wait',
      priority: 'recommended',
      criticality: 'high',
      ruleSourceAuthority: 'approved',
      purpose: '验证共享配置是否放大数据库连接等待',
      entity: 'settlement-db',
      capability: '数据库连接池检查',
      metricRules: [
        createMetricRule('db.pool.wait_p95', '<=', 20, { sourceRef: 'middleware-catalog' }),
        createMetricRule('db.pool.utilization', '<=', 80, { sourceRef: 'middleware-catalog' }),
      ],
      failureAction: '暂停灰度并启动 RC Agent',
      rationale: '运行时 hash 对账发现 settlement-db 位于声明外的实际影响面。',
      sourceRefs: ['runtime-diff', 'payment-trace', 'middleware-catalog'],
    }),
  ],
  committedChecks: [
    check({
      id: 'payment-success',
      purpose: '保护支付确认业务结果',
      entity: '支付确认旅程',
      capability: '业务黄金指标',
      metricRules: [createMetricRule('payment.confirm.success_rate', '>=', 99.82, { sourceRef: 'payment-graph' })],
      failureAction: '暂停并通知支付 SRE',
      rationale: '业务图谱将 payment-api 与支付确认结果绑定。',
      sourceRefs: ['change-ticket', 'payment-graph'],
    }),
    check({
      id: 'payment-service',
      purpose: '验证 payment-api 自身稳定性',
      entity: 'payment-api',
      capability: '服务黄金信号',
      metricRules: [
        createMetricRule('http.error_rate', '<=', 0.3, { sourceRef: 'middleware-catalog' }),
        createMetricRule('http.duration.p95', '<=', 216, { sourceRef: 'middleware-catalog' }),
      ],
      failureAction: '暂停灰度',
      rationale: '电子流声明 payment-api 为直接变更对象。',
      sourceRefs: ['change-ticket', 'middleware-catalog'],
    }),
  ],
  execution: [
    { id: 'reconcile', label: '验证实际变更范围', status: 'Verified', fact: '发现 2 个声明外实体并已纳入计划' },
    { id: 'business', label: '验证支付黄金指标', status: 'Verified', fact: '支付成功率暂未退化' },
    { id: 'database', label: '验证数据库连接等待', status: 'Violated', fact: '连接池占用 96%，等待 p95 68ms' },
    { id: 'async', label: '验证发票异步链路', status: 'Inconclusive', fact: '低流量窗口证据不足，需继续观察' },
  ],
  report: {
    evidenceVerdict: 'Violated',
    action: 'Pause',
    actionLabel: '建议暂停在 25% 灰度',
    title: '数据库连接等待违反关键门禁',
    summary: '支付结果尚未退化，但 settlement-db 已出现连接池饱和，不能用业务指标暂时正常替代关键证据。',
    scopeStatement: '结论覆盖实际配置 hash 影响的 payment-api、settlement-db 与 invoice-worker。',
    evidenceCounts: { verified: 2, violated: 1, unresolved: 1 },
    keyEvidence: [
      'settlement-db 连接池占用 96%（门禁 80%）',
      '连接等待 p95 68ms（门禁 20ms）',
      '支付成功率当前稳定，但属于滞后结果信号',
    ],
    checkResults: [
      {
        checkId: 'payment-success',
        status: 'Verified',
        summary: '支付成功率 99.91%，当前未退化',
        measurements: [
          {
            id: 'payment-success-rate',
            metricId: 'payment.confirm.success_rate',
            label: '支付确认成功率',
            entity: '支付确认旅程',
            kind: 'numeric',
            value: 99.91,
            unit: '%',
            displayValue: '99.91%',
            series: createTrendSeries(99.94, 99.93, 99.92, 99.9, 99.91, 99.91),
            gate: { operator: '>=', value: 99.82, unit: '%', displayValue: '下降不超过 0.10pp' },
          },
        ],
      },
      {
        checkId: 'payment-service',
        status: 'Verified',
        summary: 'payment-api p95 210ms，仍在 216ms 门禁内',
        measurements: [
          {
            id: 'payment-api-error-rate',
            metricId: 'http.error_rate',
            label: '服务错误率',
            entity: 'payment-api',
            kind: 'numeric',
            value: 0.12,
            unit: '%',
            displayValue: '0.12%',
            series: createTrendSeries(0.09, 0.1, 0.11, 0.14, 0.13, 0.12),
            gate: { operator: '<=', value: 0.3, unit: '%', displayValue: '≤ 0.3%' },
          },
          {
            id: 'payment-api-p95',
            metricId: 'http.duration.p95',
            label: '服务延迟 p95',
            entity: 'payment-api',
            kind: 'numeric',
            value: 210,
            unit: 'ms',
            displayValue: '210ms',
            series: createTrendSeries(196, 201, 205, 214, 211, 210),
            gate: { operator: '<=', value: 216, unit: 'ms', displayValue: '增幅 ≤ 8%' },
          },
        ],
      },
      {
        checkId: 'invoice-backlog',
        status: 'Inconclusive',
        summary: '低流量窗口不足以判断 invoice-worker 积压趋势',
        measurements: [
          {
            id: 'invoice-backlog-rate',
            metricId: 'invoice.queue.lag',
            label: '异步积压增长率',
            entity: 'invoice-worker',
            kind: 'numeric',
            value: 3.4,
            unit: '%',
            displayValue: '+3.4%',
            series: createTrendSeries(1.2, 1.8, 2.4, 2.9, 3.2, 3.4),
            gate: { operator: '<=', value: 5, unit: '%', displayValue: '≤ 5%' },
          },
        ],
      },
      {
        checkId: 'candidate-db-wait',
        status: 'Violated',
        summary: 'settlement-db 连接池占用 96%，等待 p95 68ms',
        measurements: [
          {
            id: 'settlement-pool-utilization',
            metricId: 'db.pool.utilization',
            label: '连接池占用',
            entity: 'settlement-db',
            kind: 'numeric',
            value: 96,
            unit: '%',
            displayValue: '96%',
            series: createTrendSeries(72, 78, 83, 89, 94, 96),
            gate: { operator: '<=', value: 80, unit: '%', displayValue: '≤ 80%' },
          },
          {
            id: 'settlement-pool-wait',
            metricId: 'db.pool.wait_p95',
            label: '连接等待 p95',
            entity: 'settlement-db',
            kind: 'numeric',
            value: 68,
            unit: 'ms',
            displayValue: '68ms',
            series: createTrendSeries(12, 18, 26, 39, 55, 68),
            gate: { operator: '<=', value: 20, unit: 'ms', displayValue: '≤ 20ms' },
          },
          {
            id: 'settlement-pool-config',
            metricId: 'db.pool.config',
            label: '连接池上限',
            entity: 'shared-payment-stack@c2bd',
            kind: 'qualitative',
            displayValue: '120 → 60',
            gate: { displayValue: '保持基线配置' },
          },
        ],
      },
    ],
    interpretation: {
      whatHappened: {
        text: 'settlement-db 连接池占用与等待 p95 同时越过门禁。',
        evidenceIds: ['settlement-pool-utilization', 'settlement-pool-wait'],
      },
      likelyCause: {
        text: '共享配置包将连接池上限从 120 降为 60。',
        evidenceIds: ['settlement-pool-config'],
      },
      recommendedAction: {
        text: '暂停灰度，恢复连接池上限后复验。',
        evidenceIds: ['settlement-pool-utilization', 'settlement-pool-config'],
      },
    },
    residualRisks: ['invoice-worker 当前样本不足，证据为 Inconclusive。'],
    rcAgent: {
      title: 'RC Agent · 诊断完成',
      rootCause: '共享配置包将 DB 连接池上限从 120 降为 60，灰度实例连接等待放大。',
      chain: ['payment-api p95 上升', 'settlement-db pool wait', 'shared-payment-stack@c2bd'],
      recommendation: '恢复连接池上限，复验通过后再继续灰度。',
    },
  },
};

for (const scenario of [naturalLanguagePass, changeTicketRisk]) {
  scenario.reconciliation = reconcileChange(scenario.declaredChange, scenario.observedChange);
}

export const scenarios = deepFreeze([naturalLanguagePass, changeTicketRisk]);

export function getScenario(scenarioId) {
  return scenarios.find((scenario) => scenario.id === scenarioId) ?? null;
}
