export const releaseScenario = {
  id: 'release',
  number: '01',
  role: '发布负责人',
  roleName: '沈言 · Checkout Owner',
  title: '发布后健康验证',
  trigger: 'checkout-api v4.18.0 已完成 25% 灰度',
  decisionQuestion: 'rc3 是否可以继续扩量？',
  valuePromise: '把 6 个系统、20 分钟人工核对压缩成一份可复核的放行结论',
  accent: 'violet',
  context: {
    service: 'checkout-service',
    env: 'prod · cn-east',
    timeRange: '10:18–10:48 UTC+8',
    change: 'release-2026.07.22-rc3',
    owner: 'Checkout Platform',
  },
  steps: [
    {
      id: 'release-plan',
      module: 'checks',
      navLabel: '验证计划',
      title: '审阅 AI 生成的发布验证计划',
      intent: '确认范围、对照组、检查窗口和阻断条件，而不是直接运行一段 Prompt。',
      aiContribution: '根据变更 diff、依赖图和历史回归，补出连接池与支付旅程检查。',
      humanDecision: '批准计划并锁定 production/cn-east 范围。',
      requiredAction: 'approve_release_plan',
      actionLabel: '批准 12 项验证计划',
      evidenceIds: ['CHK-REL-42', 'DEP-payment-adapter'],
    },
    {
      id: 'release-impact',
      module: 'metrics',
      navLabel: '影响确认',
      title: '比较灰度组、发布前基线与对照组',
      intent: '判断异常是否超过 SLO 门槛，以及是否与 rc3 同时出现。',
      aiContribution: '自动选择同星期基线和仍运行旧版本的新加坡节点作为对照。',
      humanDecision: '确认错误率与延迟偏离具有业务影响。',
      requiredAction: 'confirm_release_impact',
      actionLabel: '确认影响与变更相关',
      evidenceIds: ['MET-5XX-087', 'MET-P95-1840', 'SLO-BURN-124'],
    },
    {
      id: 'release-user-proof',
      module: 'synthetics',
      navLabel: '用户验证',
      title: '回放结算用户旅程',
      intent: '确认指标异常是否真的伤害用户，而不是内部噪声。',
      aiContribution: '把失败定位到“支付确认”步骤，并找出旧版本对照节点。',
      humanDecision: '将上海 Android 旅程失败纳入阻断证据。',
      requiredAction: 'accept_synthetic_failure',
      actionLabel: '接纳用户旅程证据',
      evidenceIds: ['SYN-CHECKOUT-SH', 'SYN-CONTROL-SG'],
    },
    {
      id: 'release-root-cause',
      module: 'logs',
      navLabel: '差异定位',
      title: '验证配置差异与超时模式',
      intent: '找到只有 rc3 实例出现、且能解释用户失败的日志模式。',
      aiContribution: '聚类 842 条超时日志，并对比 v41/v42 的 pool.maxConnections。',
      humanDecision: '接纳“连接池从 120 回退到 40”为最可能原因。',
      requiredAction: 'pin_release_log_pattern',
      actionLabel: '钉入配置与超时模式',
      evidenceIds: ['LOG-TIMEOUT-842', 'LOG-CONFIG-120-40'],
    },
    {
      id: 'release-decision',
      module: 'decision',
      navLabel: '放行决策',
      title: '形成发布决策与复验条件',
      intent: '把事实、假设和行动边界汇总成人工可签字的发布结论。',
      aiContribution: '生成证据包、回滚建议与修复后必须重跑的 4 项检查。',
      humanDecision: '暂停扩量，由负责人选择修复后复验或回滚。',
      requiredAction: 'prepare_release_decision',
      actionLabel: '生成放行决策包',
      evidenceIds: ['DEC-RELEASE-GATE'],
    },
  ],
  datasets: {
    metrics: {
      slo: { name: 'Checkout success', target: '99.90%', current: '93.72%', burnRate: '12.4×', status: 'critical' },
      series: [42, 44, 43, 46, 48, 50, 51, 56, 72, 88, 91, 87],
      baseline: [43, 42, 44, 45, 44, 46, 47, 45, 46, 44, 45, 43],
      comparison: [41, 43, 42, 44, 46, 45, 47, 46, 45, 44, 46, 45],
      changeMarker: { label: 'rc3 25% 灰度', at: 7 },
      topology: [
        { id: 'web', label: 'checkout-web', state: 'warning', latency: '310 ms' },
        { id: 'api', label: 'checkout-api v42', state: 'critical', latency: '1.84 s' },
        { id: 'payment', label: 'payment-adapter', state: 'critical', latency: '1.42 s' },
        { id: 'db', label: 'payment-db', state: 'healthy', latency: '38 ms' },
      ],
    },
    alerts: {
      rawCount: 6,
      clusters: [
        { id: 'REL-A1', title: '结算 SLO 快速燃烧', count: 4, severity: 'P1', relation: '同一发布窗口' },
        { id: 'REL-A2', title: '连接池等待升高', count: 2, severity: 'P2', relation: '仅 v42 实例' },
      ],
      routes: [{ team: 'Checkout Platform', channel: '#release-checkout', sla: '5 min' }],
      impact: { sessions: '18%', orders: '¥ 1.26M / h at risk' },
    },
    logs: {
      query: 'service:checkout-api env:prod version:v4.18.0 @level:error',
      patterns: [
        {
          id: 'LOG-TIMEOUT-842',
          signature: 'PaymentClient timeout after 1500ms',
          count: 842,
          delta: '+734%',
          firstSeen: '10:24:26',
        },
        {
          id: 'LOG-CONFIG-120-40',
          signature: 'pool.maxConnections changed 120 → 40',
          count: 18,
          delta: 'v42 only',
          firstSeen: '10:21:09',
        },
        { id: 'LOG-CACHE-OK', signature: 'Cache warmup completed', count: 36, delta: 'normal', firstSeen: '10:20:57' },
      ],
      facets: {
        version: { v41: 12, v42: 860 },
        region: { cnEast: 826, apSoutheast: 46 },
        pod: { pod7d94: 431, pod8a12: 395 },
      },
      samples: [
        {
          id: 'LOG-SAMPLE-RELEASE-TIMEOUT',
          time: '10:24:26.083',
          level: 'ERROR',
          text: 'PaymentClient timeout after 1500ms poolWait=1487ms version=v42',
        },
        {
          id: 'LOG-SAMPLE-RELEASE-CHECKOUT',
          time: '10:24:26.227',
          level: 'ERROR',
          text: 'Checkout confirm failed order=••• cause=PoolAcquireTimeout',
        },
      ],
    },
    checks: {
      coverage: { planned: 12, runnable: 12, passed: 8, failed: 3, unknown: 1, percent: 92 },
      definitions: [
        { id: 'CHK-REL-42', name: '关键 SLO 前后对比', source: 'existing', gate: 'blocker', state: 'approved' },
        {
          id: 'CHK-POOL',
          name: '连接池配置与等待时间',
          source: 'AI candidate · history INC-883',
          gate: 'high',
          state: 'review',
        },
        { id: 'CHK-SYN', name: '结算旅程多地域对照', source: 'existing', gate: 'blocker', state: 'approved' },
      ],
      runs: [
        { at: '+5 min', status: 'failed', summary: '3 failed · 1 unknown' },
        { at: '+15 min', status: 'scheduled', summary: '等待负责人决策' },
        { at: 'next day', status: 'scheduled', summary: '验证长期回归' },
      ],
      findings: [
        { id: 'F-2041', title: '连接池上限回退导致结算排队', severity: 'blocker', owner: '陈曦', status: 'candidate' },
      ],
    },
    synthetics: {
      journey: { name: '登录 → 加购 → 提交订单 → 支付确认', device: 'Android / Chrome', currentStep: 4 },
      steps: [
        { name: '登录', duration: 420, status: 'passed' },
        { name: '加购', duration: 310, status: 'passed' },
        { name: '提交订单', duration: 680, status: 'passed' },
        { name: '支付确认', duration: 2840, status: 'failed' },
      ],
      regions: [
        { name: '上海', version: 'v42', success: '71%', p95: '2.84 s', status: 'critical' },
        { name: '北京', version: 'v42', success: '78%', p95: '2.31 s', status: 'critical' },
        { name: '新加坡', version: 'v41', success: '99.8%', p95: '620 ms', status: 'healthy' },
      ],
      waterfall: [110, 80, 140, 520, 1480, 510],
    },
  },
  ai: {
    facts: [
      { id: 'REL-F1', text: '5xx 在 rc3 完成后 3m12s 开始升高。', sourceIds: ['MET-5XX-087'] },
      { id: 'REL-F2', text: '旧版本对照节点保持 99.8% 成功率。', sourceIds: ['SYN-CONTROL-SG'] },
    ],
    hypotheses: [
      {
        id: 'REL-H1',
        text: 'v42 将连接池上限从 120 回退到 40，导致获取连接排队。',
        confidence: 86,
        sourceIds: ['LOG-CONFIG-120-40', 'LOG-TIMEOUT-842'],
      },
    ],
    gaps: [{ id: 'REL-G1', text: '移动端订单回调检查尚无返回。', verifyAction: '等待 +15 min Run 或手动补跑' }],
    recommendations: [{ id: 'REL-R1', text: '暂停扩量；恢复连接池配置后重跑 4 项阻断检查。', sourceIds: ['REL-H1'] }],
  },
  decisions: [
    { id: 'pause_release', label: '暂停扩量并修复', tone: 'warning' },
    { id: 'rollback_release', label: '立即回滚 rc3', tone: 'danger' },
    { id: 'continue_observing', label: '保持 25% 继续观察', tone: 'neutral' },
  ],
  outcomeBlueprint: {
    artifactType: 'release_gate',
    owner: '沈言 / Checkout Platform',
    verificationGate: '配置恢复后，SLO、连接池、上海/北京拨测及回调检查全部通过',
    value: { manualJumpsAvoided: 6, timeToConclusion: '7 min', evidenceCoverage: '11 / 12 checks' },
  },
  riskGates: { coverageState: 'partial', freshnessState: 'fresh', baselineState: 'comparable' },
};
